version: 2

defaults: &defaults
  docker:
    - image: circleci/android:api-28-alpha
  environment:
    JVM_OPTS: -Xmx3200m

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Install fastlane dependencies
          command: gem update --system && gem install bundler
      - run:
          name: Install fastlane
          command: bundle install
      - run:
          name: Get google-services.json
          command: echo $GOOGLE_SERVICES | base64 -di > app/google-services.json
      - run:
          name: Get api-5146002300548282708-397628-4a7c8d6b9073.json
          command: echo $PLAY_DEVELOPER_API_KEY | base64 -di > app/api-5146002300548282708-397628-4a7c8d6b9073.json
      - run:
          name: Get keystore.jks
          command: echo $KEYSTORE | base64 -di > app/keystore.jks
      - run:
          name: Get signing.properties
          command: echo $SIGNING_PROPERTIES | base64 -di > signing.properties
      - run:
          name: Init fastlane supply
          command: bundle exec fastlane supply init
      - run:
          name: Deploy to internal track
          command: bundle exec fastlane internal
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }} 
